VeryGoodOpenSource/mockingjay

README.md, example/pubspec.yaml, pubspec.yaml
This PR contains a minor latent change to the README necessary after the transfer.
=> chore: fix repo links and badge url

.github/workflows/main.yaml, README.md, lib/mockingjay.dart, test/src/example_test.dart
- feat: export `package:mocktail`
- docs: update README to include a complete example
- test: add example to tests
=> feat: export package:mocktail and update docs

CHANGELOG.md, pubspec.yaml
- docs: update pubspec.yaml description
=> docs: update pubspec.yaml description

analysis_options.yaml, example/analysis_options.yaml, example/lib/app.dart, example/lib/ui/home_screen.dart, example/lib/ui/pincode_screen.dart, example/pubspec.yaml, lib/src/mock_navigator.dart, pubspec.yaml, test/src/example_test.dart, test/src/matchers_test.dart, test/src/mock_navigator_test.dart
This PR contains minor changes related to updating the linter to the latest version at the time of writing.
=> chore: update linter and apply new rules

CHANGELOG.md, pubspec.yaml
This PR bumps the version to `0.1.1` and updates the CHANGELOG to reflect the latest changes, in preparation of a new release.
=> chore: update changelog and bump version to 0.1.1

.github/workflows/main.yaml
- ci: upgrade to flutter-action@v1.5.3
=> ci: upgrade to flutter-action@v1.5.3

.github/workflows/main.yaml, CHANGELOG.md, README.md, example/lib/ui/quiz_dialog.dart, example/test/ui/home_screen_test.dart, example/test/ui/pincode_screen_test.dart, example/test/ui/quiz_dialog_test.dart, pubspec.yaml, test/src/mock_navigator_test.dart
- chore: bump version to 0.2.0
- chore: remove unnecessary imports
- ci: upgrade very_good_coverage to v1.2.0
- feat: add mock call for `canPop` (thanks [@allisonryan0002](https://github.com/allisonryan0002)!)
- feat: add mock call for `maybePop` (thanks [@korzonkiee](https://github.com/korzonkiee)!)
- feat: add `whereSettings`, `whereName`, `whereArguments`, `whereMaintainState` and `whereFullscreenDialog` matcher arguments to `isRoute` matcher
- **DEPRECATE**: fix: `named` argument on `isRoute` deprecated in favor of `whereName`
=> chore: v0.2.0

example/pubspec.yaml, example/test/ui/home_screen_test.dart, lib/src/mock_navigator.dart, pubspec.yaml, test/src/example_test.dart, test/src/mock_navigator_test.dart
- feat: support mocktail ^0.3.0
=> feat!: support mocktail ^0.3.0

CHANGELOG.md, pubspec.yaml
=> chore: v0.3.0

README.md
- docs: update to v0.3.0 in README
=> docs: update to v0.3.0 in README

.github/CODEOWNERS, analysis_options.yaml, example/analysis_options.yaml, example/pubspec.yaml, lib/src/matcher_extensions.dart, lib/src/matchers.dart, lib/src/mock_navigator.dart, pubspec.yaml, test/src/matchers_test.dart
feat: update very good analysis
=> feat: update very good analysis

.github/cspell.json, .github/workflows/example.yaml, .github/workflows/main.yaml, analysis_options.yaml, example/analysis_options.yaml, example/lib/app.dart, example/lib/ui/home_screen.dart, example/lib/ui/pincode_screen.dart, example/lib/ui/quiz_dialog.dart, example/pubspec.yaml, example/test/ui/pincode_screen_test.dart, example/test/ui/quiz_dialog_test.dart, lib/src/mock_navigator.dart, pubspec.yaml, test/src/example_test.dart
feat: update very good analysis, flutter version and workflows
=> feat: update very good analysis, flutter version and workflows 

README.md, pubspec.yaml
=> docs: update readme example

example/pubspec.yaml, pubspec.yaml
- chore(deps): bump to `mocktail` v1.0.0
=> chore(deps): bump to `mocktail` v1.0.0

CHANGELOG.md, pubspec.yaml
=> chore: bump to 0.4.0 and update changelog

CHANGELOG.md, pubspec.yaml
Updating sdk constraint to include dart 3
=> feat: update sdk constraint to include dart 3

analysis_options.yaml, example/analysis_options.yaml, example/pubspec.yaml, pubspec.yaml
Updates Very Good Analysis to 5.1.0, see [this](https://github.com/VeryGoodOpenSource/very_good_analysis/pull/84) for more information.
=> chore: update Very Good Analysis to 5.1.0

example/pubspec.yaml
Updates the Dart SDK constraints in the example to be exactly the same as the main package.
See [this](https://github.com/VeryGoodOpenSource/mockingjay/blob/68f13013163aeebc9ad93f59c2254381a909f5e6/pubspec.yaml#L7).
=> chore(example): updated SDK constraints

README.md
docs: update installation instructions readme
=> docs: update installation instructions readme

example/pubspec.yaml, pubspec.yaml
=> chore: sync min dark sdk with min flutter sdk

.github/workflows/main.yaml, example/pubspec.yaml, pubspec.yaml
=> chore: tighten dependencies

.github/workflows/pub_publish.yaml
**READY**
Related to #73 
Adds the [Automated Publishing](https://dart.dev/tools/pub/automated-publishing) workflow.
The pertinent configuration in `pub.dev` has also been completed.
=> ci: add automated publishing workflow

CHANGELOG.md, pubspec.yaml
=> chore: v0.6.0

test/src/mock_navigator_test.dart
=> fix: fixing formatting step

CHANGELOG.md
=> chore: v2.0.0
